name = "docbuild"
version = "0.1.0"
reservoir = false
packagesDir = "../.lake/packages"

[[require]]
name = "lean_math_lab"
path = ".."

[[require]]
name = "doc-gen4"
scope = "leanprover"
rev = "v4.33.1"
