"""Serial fixed-generator verification, preserving the accepted pilot runner."""
import importlib.util, json, os, re, shutil, sys, time
from pathlib import Path
HERE=Path(__file__).resolve().parent
SPEC=json.loads((HERE/'full-stage-v2-spec.json').read_text(encoding='utf-8-sig'))
loader=importlib.util.spec_from_file_location('accepted_runtime',HERE/'linux-runner.py')
b=importlib.util.module_from_spec(loader); loader.loader.exec_module(b)
b.ROOT=b.REPO/SPEC['toolRoot']; b.EVIDENCE=b.ROOT/'evidence'; b.OBJECTS=b.EVIDENCE/'objects'
def mod(path):
    return '.'.join('«'+x+'»' if '-' in x or x[:1].isdigit() else x for x in path[:-5].split('/'))
def names(path):
    stack=[]; result=[]
    for line in Path(path).read_text(encoding='utf-8-sig').splitlines():
        m=re.match(r'^namespace\s+(\S+)',line)
        if m: stack.append(m[1]); continue
        if re.match(r'^section(?:\s|$)',line): stack.append(''); continue
        if re.match(r'^end(?:\s|$)',line):
            if stack: stack.pop()
            continue
        m=re.match(r'^(?:(?:public|protected)\s+)?theorem\s+(\S+)',line)
        if m: result.append('.'.join([x for x in stack if x]+[m[1]]))
    return result
def audited(r, roots):
    actual={}; raw=Path(r['stdout']).read_text()
    for m in re.finditer(r"'([^']+)' (?:depends on axioms:\s*\[([^\]]*)\]|does not depend on any axioms)",raw,re.S):
        axs=[x.strip() for x in (m[2] or '').split(',') if x.strip()]
        if m[1] in actual or len(set(axs))!=len(axs) or set(axs)-b.ALLOWED: raise RuntimeError('Forbidden/duplicate axioms')
        actual[m[1]]=axs
    if set(roots)-set(actual): raise RuntimeError('Missing complete declared-root audit')
    b.write(Path(r['stdout']).parent.name+'/axiom-audit.json',{'utc':b.utc(),'status':'accepted-standard-axioms','roots':roots,'actualAxioms':actual,'sourceSha256':r['sourceSha256'],'stdoutSha256':r['stdoutSha256']})
def compile(path,label,env):
    r=b.compile_source(b.REPO/path,label,env,b.OBJECTS,b.REPO); roots=names(b.REPO/path)
    emitted=set(re.findall(r"'([^']+)' (?:depends on axioms:|does not depend on any axioms)",Path(r['stdout']).read_text()))
    if set(roots)-emitted:
        p=b.ROOT/(label.replace('-','_')+'_Audit.lean'); p.parent.mkdir(parents=True,exist_ok=True)
        p.write_text('module\npublic import '+mod(path)+'\n'+'\n'.join('#print axioms '+x for x in roots)+'\n')
        ar=b.compile_source(p,label+'-audit',env,b.OBJECTS,b.ROOT); audited(ar,roots)
    else: audited(r,roots)
    return r
def check(module,label,env):
    tc=json.loads((b.EVIDENCE/'toolchain.json').read_text())
    return b.launch([tc['leanchecker'],'-v',module],label,env)
def generate(mode,cost):
    b.launch(['python3',str(b.REPO/SPEC['generator']), '--repo',str(b.REPO),'--method','normnum','--mode',mode,'--start','-1','--nodes','128','--accepted-cost-receipt',str(cost)],'generate-'+mode,max_seconds=60)
    maps=list((b.REPO/SPEC['generatedDirectory']).glob('normnum-'+mode+'-*-source-map.json'))
    if len(maps)!=1: raise RuntimeError('Non-unique generated source map')
    data=json.loads(maps[0].read_text()); dst=b.EVIDENCE/'generated-source-maps'/maps[0].name; dst.parent.mkdir(parents=True,exist_ok=True); shutil.copyfile(maps[0],dst)
    for out in data['outputs']:
        p=b.REPO/out['path']
        if b.sha(p)!=out['sha256'] or p.stat().st_size!=out['bytes']: raise RuntimeError('Generated byte binding differs')
        dst=b.EVIDENCE/'generated-sources'/out['path']; dst.parent.mkdir(parents=True,exist_ok=True); shutil.copyfile(p,dst)
    return data
def run():
    b.EVIDENCE.mkdir(parents=True,exist_ok=True)
    start=float(os.environ.get('B699_JOB_START_EPOCH',str(time.time())))
    b.DEADLINE=min(b.DEADLINE,start+(SPEC['jobMinutes']-1)*60)
    b.write('stage-spec.json',SPEC); shutil.copyfile(__file__,b.EVIDENCE/'full-stage-v2.py')
    for x in SPEC['fixedFiles']:
        p=b.REPO/x['path']
        if b.sha(p)!=x['sha256'] or p.stat().st_size!=x['bytes']: raise RuntimeError('Fixed input differs: '+x['path'])
        dst=b.EVIDENCE/'fixed-inputs'/x['path']; dst.parent.mkdir(parents=True,exist_ok=True); shutil.copyfile(p,dst)
    previous=sys.argv[:]; sys.argv=[str(HERE/'linux-runner.py'),'cache']
    try: b.main()
    finally: sys.argv=previous
    env=b.lean_env()
    for i,p in enumerate(SPEC['supportSources']): compile(p,f'support-{i:02d}-{Path(p).stem}',env)
    cost32=b.EVIDENCE/'accepted-cost-32.json'; cost32.write_text(json.dumps(SPEC['acceptedCost32'],indent=2))
    probe=generate('batch',cost32); out=probe['outputs'][0]
    r=compile(out['path'],'probe128',env); c=check(mod(out['path']),'probe128-checker',env)
    cost={'method':'normnum-constructive-chain','acceptedNodeCount':out['nodeCount'],'actualCompilerExit':r['exitCode'],'actualCheckerExit':c['exitCode'],'actualAxiomAuditAccepted':True,'actualCostSeconds':r['wallSeconds'],'fixedSourceSha256':r['sourceSha256'],'checkerSeconds':c['wallSeconds']}
    costfile=b.EVIDENCE/'accepted-cost-128.json'; costfile.write_text(json.dumps(cost,indent=2))
    b.write('probe128-closed.json',{'utc':b.utc(),'status':'kernel-audit-checker-passed','cost':cost,'sourceMap':probe})
    estimate=r['wallSeconds']/out['nodeCount']*probe['selectedCount']*1.10+60
    remaining=b.DEADLINE-time.time(); b.write('full-budget-gate.json',{'estimatedSeconds':estimate,'remainingSeconds':remaining,'selectedCount':probe['selectedCount']})
    if estimate>remaining:
        b.write('partial.json',{'status':'closed128-only-budget-rejected'}); return
    full=generate('full',costfile)
    for i,out in enumerate(full['outputs']): compile(out['path'],f'full-{i:03d}-{out["name"]}',env)
    check(mod(full['outputs'][-1]['path']),'full-chain-checker',env)
    b.write('full-chain-closed.json',{'utc':b.utc(),'status':'kernel-audit-checker-passed','sourceMap':full,'mathematicalAcceptance':'pending semantic review'})
    for i,p in enumerate(SPEC['finalSources']): compile(p,f'finite-final-{i:02d}-{Path(p).stem}',env)
    check(SPEC['finalCheckerModule'],'finite-original-checker',env)
    b.write('finite-original-closed.json',{'utc':b.utc(),'status':'kernel-audit-checker-passed','checkerModule':SPEC['finalCheckerModule'],'mathematicalAcceptance':'pending semantic review'})
if __name__=='__main__':
    try:
        if len(sys.argv)>1 and sys.argv[1]=='manifest': sys.argv=[str(HERE/'linux-runner.py'),'manifest']; b.main()
        else: run()
    except BaseException as e:
        b.write('stage-failure.json',{'utc':b.utc(),'failure':str(e),'class':type(e).__name__}); print(str(e),file=sys.stderr); sys.exit(1)
