import research.tasks.«B686-Four».round4.worker.K5LossFinite

/-! Exact finite extension: generated by generate_contact_finite.py.
Kernel decide checks two strict signs; old ratio monotonicity covers all n. -/
set_option maxRecDepth 200000
set_option maxHeartbeats 6000000
namespace B686Round5Finite
open B686Round4K5Finite

def cutoff4 (d : ℕ) : ℕ :=
  if d = 3636 then 11377 else if d = 4545 then 14222
  else 312981296038 * d / 100000000000 - 3

theorem signs4_19000 : ∀ t : Fin 200,
    4 * product 5 (cutoff4 (t.val + 19000)) <
      product 5 (cutoff4 (t.val + 19000) + (t.val + 19000)) ∧
    product 5 (cutoff4 (t.val + 19000) + 1 + (t.val + 19000)) <
      4 * product 5 (cutoff4 (t.val + 19000) + 1) := by
  decide

theorem signs4_19200 : ∀ t : Fin 200,
    4 * product 5 (cutoff4 (t.val + 19200)) <
      product 5 (cutoff4 (t.val + 19200) + (t.val + 19200)) ∧
    product 5 (cutoff4 (t.val + 19200) + 1 + (t.val + 19200)) <
      4 * product 5 (cutoff4 (t.val + 19200) + 1) := by
  decide

theorem signs4_19400 : ∀ t : Fin 200,
    4 * product 5 (cutoff4 (t.val + 19400)) <
      product 5 (cutoff4 (t.val + 19400) + (t.val + 19400)) ∧
    product 5 (cutoff4 (t.val + 19400) + 1 + (t.val + 19400)) <
      4 * product 5 (cutoff4 (t.val + 19400) + 1) := by
  decide

theorem signs4_19600 : ∀ t : Fin 200,
    4 * product 5 (cutoff4 (t.val + 19600)) <
      product 5 (cutoff4 (t.val + 19600) + (t.val + 19600)) ∧
    product 5 (cutoff4 (t.val + 19600) + 1 + (t.val + 19600)) <
      4 * product 5 (cutoff4 (t.val + 19600) + 1) := by
  decide

theorem signs4_19800 : ∀ t : Fin 200,
    4 * product 5 (cutoff4 (t.val + 19800)) <
      product 5 (cutoff4 (t.val + 19800) + (t.val + 19800)) ∧
    product 5 (cutoff4 (t.val + 19800) + 1 + (t.val + 19800)) <
      4 * product 5 (cutoff4 (t.val + 19800) + 1) := by
  decide

theorem not_four_block4 (n d : ℕ) (hl : 19000 ≤ d) (hu : d < 20000) :
    (∏ r ∈ Finset.Icc 1 (5 : ℕ), (n + d + r)) ≠
      4 * (∏ r ∈ Finset.Icc 1 (5 : ℕ), (n + r)) := by
  by_cases hb19000 : d < 19200
  ·
    have h := signs4_19000 ⟨d - 19000, by omega⟩
    have he : d - 19000 + 19000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff4 d) n h.1 h.2
  by_cases hb19200 : d < 19400
  ·
    have h := signs4_19200 ⟨d - 19200, by omega⟩
    have he : d - 19200 + 19200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff4 d) n h.1 h.2
  by_cases hb19400 : d < 19600
  ·
    have h := signs4_19400 ⟨d - 19400, by omega⟩
    have he : d - 19400 + 19400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff4 d) n h.1 h.2
  by_cases hb19600 : d < 19800
  ·
    have h := signs4_19600 ⟨d - 19600, by omega⟩
    have he : d - 19600 + 19600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff4 d) n h.1 h.2
  have h := signs4_19800 ⟨d - 19800, by omega⟩
  have he : d - 19800 + 19800 = d := by omega
  simp only [he] at h
  exact not_four_of_adjacent_signs 5 d (cutoff4 d) n h.1 h.2

/-- info: 'B686Round5Finite.not_four_block4' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms not_four_block4
end B686Round5Finite
