import research.tasks.«B686-Four».round4.worker.K5LossFinite

/-! Exact finite extension: generated by generate_contact_finite.py.
Kernel decide checks two strict signs; old ratio monotonicity covers all n. -/
set_option maxRecDepth 200000
set_option maxHeartbeats 6000000
namespace B686Round5Finite
open B686Round4K5Finite

def cutoff1 (d : ℕ) : ℕ :=
  if d = 3636 then 11377 else if d = 4545 then 14222
  else 312981296038 * d / 100000000000 - 3

theorem signs1_7000 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 7000)) <
      product 5 (cutoff1 (t.val + 7000) + (t.val + 7000)) ∧
    product 5 (cutoff1 (t.val + 7000) + 1 + (t.val + 7000)) <
      4 * product 5 (cutoff1 (t.val + 7000) + 1) := by
  decide

theorem signs1_7200 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 7200)) <
      product 5 (cutoff1 (t.val + 7200) + (t.val + 7200)) ∧
    product 5 (cutoff1 (t.val + 7200) + 1 + (t.val + 7200)) <
      4 * product 5 (cutoff1 (t.val + 7200) + 1) := by
  decide

theorem signs1_7400 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 7400)) <
      product 5 (cutoff1 (t.val + 7400) + (t.val + 7400)) ∧
    product 5 (cutoff1 (t.val + 7400) + 1 + (t.val + 7400)) <
      4 * product 5 (cutoff1 (t.val + 7400) + 1) := by
  decide

theorem signs1_7600 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 7600)) <
      product 5 (cutoff1 (t.val + 7600) + (t.val + 7600)) ∧
    product 5 (cutoff1 (t.val + 7600) + 1 + (t.val + 7600)) <
      4 * product 5 (cutoff1 (t.val + 7600) + 1) := by
  decide

theorem signs1_7800 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 7800)) <
      product 5 (cutoff1 (t.val + 7800) + (t.val + 7800)) ∧
    product 5 (cutoff1 (t.val + 7800) + 1 + (t.val + 7800)) <
      4 * product 5 (cutoff1 (t.val + 7800) + 1) := by
  decide

theorem signs1_8000 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 8000)) <
      product 5 (cutoff1 (t.val + 8000) + (t.val + 8000)) ∧
    product 5 (cutoff1 (t.val + 8000) + 1 + (t.val + 8000)) <
      4 * product 5 (cutoff1 (t.val + 8000) + 1) := by
  decide

theorem signs1_8200 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 8200)) <
      product 5 (cutoff1 (t.val + 8200) + (t.val + 8200)) ∧
    product 5 (cutoff1 (t.val + 8200) + 1 + (t.val + 8200)) <
      4 * product 5 (cutoff1 (t.val + 8200) + 1) := by
  decide

theorem signs1_8400 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 8400)) <
      product 5 (cutoff1 (t.val + 8400) + (t.val + 8400)) ∧
    product 5 (cutoff1 (t.val + 8400) + 1 + (t.val + 8400)) <
      4 * product 5 (cutoff1 (t.val + 8400) + 1) := by
  decide

theorem signs1_8600 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 8600)) <
      product 5 (cutoff1 (t.val + 8600) + (t.val + 8600)) ∧
    product 5 (cutoff1 (t.val + 8600) + 1 + (t.val + 8600)) <
      4 * product 5 (cutoff1 (t.val + 8600) + 1) := by
  decide

theorem signs1_8800 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 8800)) <
      product 5 (cutoff1 (t.val + 8800) + (t.val + 8800)) ∧
    product 5 (cutoff1 (t.val + 8800) + 1 + (t.val + 8800)) <
      4 * product 5 (cutoff1 (t.val + 8800) + 1) := by
  decide

theorem signs1_9000 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 9000)) <
      product 5 (cutoff1 (t.val + 9000) + (t.val + 9000)) ∧
    product 5 (cutoff1 (t.val + 9000) + 1 + (t.val + 9000)) <
      4 * product 5 (cutoff1 (t.val + 9000) + 1) := by
  decide

theorem signs1_9200 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 9200)) <
      product 5 (cutoff1 (t.val + 9200) + (t.val + 9200)) ∧
    product 5 (cutoff1 (t.val + 9200) + 1 + (t.val + 9200)) <
      4 * product 5 (cutoff1 (t.val + 9200) + 1) := by
  decide

theorem signs1_9400 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 9400)) <
      product 5 (cutoff1 (t.val + 9400) + (t.val + 9400)) ∧
    product 5 (cutoff1 (t.val + 9400) + 1 + (t.val + 9400)) <
      4 * product 5 (cutoff1 (t.val + 9400) + 1) := by
  decide

theorem signs1_9600 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 9600)) <
      product 5 (cutoff1 (t.val + 9600) + (t.val + 9600)) ∧
    product 5 (cutoff1 (t.val + 9600) + 1 + (t.val + 9600)) <
      4 * product 5 (cutoff1 (t.val + 9600) + 1) := by
  decide

theorem signs1_9800 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 9800)) <
      product 5 (cutoff1 (t.val + 9800) + (t.val + 9800)) ∧
    product 5 (cutoff1 (t.val + 9800) + 1 + (t.val + 9800)) <
      4 * product 5 (cutoff1 (t.val + 9800) + 1) := by
  decide

theorem signs1_10000 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 10000)) <
      product 5 (cutoff1 (t.val + 10000) + (t.val + 10000)) ∧
    product 5 (cutoff1 (t.val + 10000) + 1 + (t.val + 10000)) <
      4 * product 5 (cutoff1 (t.val + 10000) + 1) := by
  decide

theorem signs1_10200 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 10200)) <
      product 5 (cutoff1 (t.val + 10200) + (t.val + 10200)) ∧
    product 5 (cutoff1 (t.val + 10200) + 1 + (t.val + 10200)) <
      4 * product 5 (cutoff1 (t.val + 10200) + 1) := by
  decide

theorem signs1_10400 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 10400)) <
      product 5 (cutoff1 (t.val + 10400) + (t.val + 10400)) ∧
    product 5 (cutoff1 (t.val + 10400) + 1 + (t.val + 10400)) <
      4 * product 5 (cutoff1 (t.val + 10400) + 1) := by
  decide

theorem signs1_10600 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 10600)) <
      product 5 (cutoff1 (t.val + 10600) + (t.val + 10600)) ∧
    product 5 (cutoff1 (t.val + 10600) + 1 + (t.val + 10600)) <
      4 * product 5 (cutoff1 (t.val + 10600) + 1) := by
  decide

theorem signs1_10800 : ∀ t : Fin 200,
    4 * product 5 (cutoff1 (t.val + 10800)) <
      product 5 (cutoff1 (t.val + 10800) + (t.val + 10800)) ∧
    product 5 (cutoff1 (t.val + 10800) + 1 + (t.val + 10800)) <
      4 * product 5 (cutoff1 (t.val + 10800) + 1) := by
  decide

theorem not_four_block1 (n d : ℕ) (hl : 7000 ≤ d) (hu : d < 11000) :
    (∏ r ∈ Finset.Icc 1 (5 : ℕ), (n + d + r)) ≠
      4 * (∏ r ∈ Finset.Icc 1 (5 : ℕ), (n + r)) := by
  by_cases hb7000 : d < 7200
  ·
    have h := signs1_7000 ⟨d - 7000, by omega⟩
    have he : d - 7000 + 7000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb7200 : d < 7400
  ·
    have h := signs1_7200 ⟨d - 7200, by omega⟩
    have he : d - 7200 + 7200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb7400 : d < 7600
  ·
    have h := signs1_7400 ⟨d - 7400, by omega⟩
    have he : d - 7400 + 7400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb7600 : d < 7800
  ·
    have h := signs1_7600 ⟨d - 7600, by omega⟩
    have he : d - 7600 + 7600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb7800 : d < 8000
  ·
    have h := signs1_7800 ⟨d - 7800, by omega⟩
    have he : d - 7800 + 7800 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb8000 : d < 8200
  ·
    have h := signs1_8000 ⟨d - 8000, by omega⟩
    have he : d - 8000 + 8000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb8200 : d < 8400
  ·
    have h := signs1_8200 ⟨d - 8200, by omega⟩
    have he : d - 8200 + 8200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb8400 : d < 8600
  ·
    have h := signs1_8400 ⟨d - 8400, by omega⟩
    have he : d - 8400 + 8400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb8600 : d < 8800
  ·
    have h := signs1_8600 ⟨d - 8600, by omega⟩
    have he : d - 8600 + 8600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb8800 : d < 9000
  ·
    have h := signs1_8800 ⟨d - 8800, by omega⟩
    have he : d - 8800 + 8800 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb9000 : d < 9200
  ·
    have h := signs1_9000 ⟨d - 9000, by omega⟩
    have he : d - 9000 + 9000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb9200 : d < 9400
  ·
    have h := signs1_9200 ⟨d - 9200, by omega⟩
    have he : d - 9200 + 9200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb9400 : d < 9600
  ·
    have h := signs1_9400 ⟨d - 9400, by omega⟩
    have he : d - 9400 + 9400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb9600 : d < 9800
  ·
    have h := signs1_9600 ⟨d - 9600, by omega⟩
    have he : d - 9600 + 9600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb9800 : d < 10000
  ·
    have h := signs1_9800 ⟨d - 9800, by omega⟩
    have he : d - 9800 + 9800 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb10000 : d < 10200
  ·
    have h := signs1_10000 ⟨d - 10000, by omega⟩
    have he : d - 10000 + 10000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb10200 : d < 10400
  ·
    have h := signs1_10200 ⟨d - 10200, by omega⟩
    have he : d - 10200 + 10200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb10400 : d < 10600
  ·
    have h := signs1_10400 ⟨d - 10400, by omega⟩
    have he : d - 10400 + 10400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  by_cases hb10600 : d < 10800
  ·
    have h := signs1_10600 ⟨d - 10600, by omega⟩
    have he : d - 10600 + 10600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2
  have h := signs1_10800 ⟨d - 10800, by omega⟩
  have he : d - 10800 + 10800 = d := by omega
  simp only [he] at h
  exact not_four_of_adjacent_signs 5 d (cutoff1 d) n h.1 h.2

/-- info: 'B686Round5Finite.not_four_block1' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms not_four_block1
end B686Round5Finite
