import research.tasks.«B686-Four».round4.worker.K5LossFinite

/-! Exact finite extension: generated by generate_contact_finite.py.
Kernel decide checks two strict signs; old ratio monotonicity covers all n. -/
set_option maxRecDepth 200000
set_option maxHeartbeats 6000000
namespace B686Round5Finite
open B686Round4K5Finite

def cutoff2 (d : ℕ) : ℕ :=
  if d = 3636 then 11377 else if d = 4545 then 14222
  else 312981296038 * d / 100000000000 - 3

theorem signs2_11000 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 11000)) <
      product 5 (cutoff2 (t.val + 11000) + (t.val + 11000)) ∧
    product 5 (cutoff2 (t.val + 11000) + 1 + (t.val + 11000)) <
      4 * product 5 (cutoff2 (t.val + 11000) + 1) := by
  decide

theorem signs2_11200 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 11200)) <
      product 5 (cutoff2 (t.val + 11200) + (t.val + 11200)) ∧
    product 5 (cutoff2 (t.val + 11200) + 1 + (t.val + 11200)) <
      4 * product 5 (cutoff2 (t.val + 11200) + 1) := by
  decide

theorem signs2_11400 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 11400)) <
      product 5 (cutoff2 (t.val + 11400) + (t.val + 11400)) ∧
    product 5 (cutoff2 (t.val + 11400) + 1 + (t.val + 11400)) <
      4 * product 5 (cutoff2 (t.val + 11400) + 1) := by
  decide

theorem signs2_11600 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 11600)) <
      product 5 (cutoff2 (t.val + 11600) + (t.val + 11600)) ∧
    product 5 (cutoff2 (t.val + 11600) + 1 + (t.val + 11600)) <
      4 * product 5 (cutoff2 (t.val + 11600) + 1) := by
  decide

theorem signs2_11800 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 11800)) <
      product 5 (cutoff2 (t.val + 11800) + (t.val + 11800)) ∧
    product 5 (cutoff2 (t.val + 11800) + 1 + (t.val + 11800)) <
      4 * product 5 (cutoff2 (t.val + 11800) + 1) := by
  decide

theorem signs2_12000 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 12000)) <
      product 5 (cutoff2 (t.val + 12000) + (t.val + 12000)) ∧
    product 5 (cutoff2 (t.val + 12000) + 1 + (t.val + 12000)) <
      4 * product 5 (cutoff2 (t.val + 12000) + 1) := by
  decide

theorem signs2_12200 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 12200)) <
      product 5 (cutoff2 (t.val + 12200) + (t.val + 12200)) ∧
    product 5 (cutoff2 (t.val + 12200) + 1 + (t.val + 12200)) <
      4 * product 5 (cutoff2 (t.val + 12200) + 1) := by
  decide

theorem signs2_12400 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 12400)) <
      product 5 (cutoff2 (t.val + 12400) + (t.val + 12400)) ∧
    product 5 (cutoff2 (t.val + 12400) + 1 + (t.val + 12400)) <
      4 * product 5 (cutoff2 (t.val + 12400) + 1) := by
  decide

theorem signs2_12600 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 12600)) <
      product 5 (cutoff2 (t.val + 12600) + (t.val + 12600)) ∧
    product 5 (cutoff2 (t.val + 12600) + 1 + (t.val + 12600)) <
      4 * product 5 (cutoff2 (t.val + 12600) + 1) := by
  decide

theorem signs2_12800 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 12800)) <
      product 5 (cutoff2 (t.val + 12800) + (t.val + 12800)) ∧
    product 5 (cutoff2 (t.val + 12800) + 1 + (t.val + 12800)) <
      4 * product 5 (cutoff2 (t.val + 12800) + 1) := by
  decide

theorem signs2_13000 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 13000)) <
      product 5 (cutoff2 (t.val + 13000) + (t.val + 13000)) ∧
    product 5 (cutoff2 (t.val + 13000) + 1 + (t.val + 13000)) <
      4 * product 5 (cutoff2 (t.val + 13000) + 1) := by
  decide

theorem signs2_13200 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 13200)) <
      product 5 (cutoff2 (t.val + 13200) + (t.val + 13200)) ∧
    product 5 (cutoff2 (t.val + 13200) + 1 + (t.val + 13200)) <
      4 * product 5 (cutoff2 (t.val + 13200) + 1) := by
  decide

theorem signs2_13400 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 13400)) <
      product 5 (cutoff2 (t.val + 13400) + (t.val + 13400)) ∧
    product 5 (cutoff2 (t.val + 13400) + 1 + (t.val + 13400)) <
      4 * product 5 (cutoff2 (t.val + 13400) + 1) := by
  decide

theorem signs2_13600 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 13600)) <
      product 5 (cutoff2 (t.val + 13600) + (t.val + 13600)) ∧
    product 5 (cutoff2 (t.val + 13600) + 1 + (t.val + 13600)) <
      4 * product 5 (cutoff2 (t.val + 13600) + 1) := by
  decide

theorem signs2_13800 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 13800)) <
      product 5 (cutoff2 (t.val + 13800) + (t.val + 13800)) ∧
    product 5 (cutoff2 (t.val + 13800) + 1 + (t.val + 13800)) <
      4 * product 5 (cutoff2 (t.val + 13800) + 1) := by
  decide

theorem signs2_14000 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 14000)) <
      product 5 (cutoff2 (t.val + 14000) + (t.val + 14000)) ∧
    product 5 (cutoff2 (t.val + 14000) + 1 + (t.val + 14000)) <
      4 * product 5 (cutoff2 (t.val + 14000) + 1) := by
  decide

theorem signs2_14200 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 14200)) <
      product 5 (cutoff2 (t.val + 14200) + (t.val + 14200)) ∧
    product 5 (cutoff2 (t.val + 14200) + 1 + (t.val + 14200)) <
      4 * product 5 (cutoff2 (t.val + 14200) + 1) := by
  decide

theorem signs2_14400 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 14400)) <
      product 5 (cutoff2 (t.val + 14400) + (t.val + 14400)) ∧
    product 5 (cutoff2 (t.val + 14400) + 1 + (t.val + 14400)) <
      4 * product 5 (cutoff2 (t.val + 14400) + 1) := by
  decide

theorem signs2_14600 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 14600)) <
      product 5 (cutoff2 (t.val + 14600) + (t.val + 14600)) ∧
    product 5 (cutoff2 (t.val + 14600) + 1 + (t.val + 14600)) <
      4 * product 5 (cutoff2 (t.val + 14600) + 1) := by
  decide

theorem signs2_14800 : ∀ t : Fin 200,
    4 * product 5 (cutoff2 (t.val + 14800)) <
      product 5 (cutoff2 (t.val + 14800) + (t.val + 14800)) ∧
    product 5 (cutoff2 (t.val + 14800) + 1 + (t.val + 14800)) <
      4 * product 5 (cutoff2 (t.val + 14800) + 1) := by
  decide

theorem not_four_block2 (n d : ℕ) (hl : 11000 ≤ d) (hu : d < 15000) :
    (∏ r ∈ Finset.Icc 1 (5 : ℕ), (n + d + r)) ≠
      4 * (∏ r ∈ Finset.Icc 1 (5 : ℕ), (n + r)) := by
  by_cases hb11000 : d < 11200
  ·
    have h := signs2_11000 ⟨d - 11000, by omega⟩
    have he : d - 11000 + 11000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb11200 : d < 11400
  ·
    have h := signs2_11200 ⟨d - 11200, by omega⟩
    have he : d - 11200 + 11200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb11400 : d < 11600
  ·
    have h := signs2_11400 ⟨d - 11400, by omega⟩
    have he : d - 11400 + 11400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb11600 : d < 11800
  ·
    have h := signs2_11600 ⟨d - 11600, by omega⟩
    have he : d - 11600 + 11600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb11800 : d < 12000
  ·
    have h := signs2_11800 ⟨d - 11800, by omega⟩
    have he : d - 11800 + 11800 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb12000 : d < 12200
  ·
    have h := signs2_12000 ⟨d - 12000, by omega⟩
    have he : d - 12000 + 12000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb12200 : d < 12400
  ·
    have h := signs2_12200 ⟨d - 12200, by omega⟩
    have he : d - 12200 + 12200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb12400 : d < 12600
  ·
    have h := signs2_12400 ⟨d - 12400, by omega⟩
    have he : d - 12400 + 12400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb12600 : d < 12800
  ·
    have h := signs2_12600 ⟨d - 12600, by omega⟩
    have he : d - 12600 + 12600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb12800 : d < 13000
  ·
    have h := signs2_12800 ⟨d - 12800, by omega⟩
    have he : d - 12800 + 12800 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb13000 : d < 13200
  ·
    have h := signs2_13000 ⟨d - 13000, by omega⟩
    have he : d - 13000 + 13000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb13200 : d < 13400
  ·
    have h := signs2_13200 ⟨d - 13200, by omega⟩
    have he : d - 13200 + 13200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb13400 : d < 13600
  ·
    have h := signs2_13400 ⟨d - 13400, by omega⟩
    have he : d - 13400 + 13400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb13600 : d < 13800
  ·
    have h := signs2_13600 ⟨d - 13600, by omega⟩
    have he : d - 13600 + 13600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb13800 : d < 14000
  ·
    have h := signs2_13800 ⟨d - 13800, by omega⟩
    have he : d - 13800 + 13800 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb14000 : d < 14200
  ·
    have h := signs2_14000 ⟨d - 14000, by omega⟩
    have he : d - 14000 + 14000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb14200 : d < 14400
  ·
    have h := signs2_14200 ⟨d - 14200, by omega⟩
    have he : d - 14200 + 14200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb14400 : d < 14600
  ·
    have h := signs2_14400 ⟨d - 14400, by omega⟩
    have he : d - 14400 + 14400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  by_cases hb14600 : d < 14800
  ·
    have h := signs2_14600 ⟨d - 14600, by omega⟩
    have he : d - 14600 + 14600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2
  have h := signs2_14800 ⟨d - 14800, by omega⟩
  have he : d - 14800 + 14800 = d := by omega
  simp only [he] at h
  exact not_four_of_adjacent_signs 5 d (cutoff2 d) n h.1 h.2

/-- info: 'B686Round5Finite.not_four_block2' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms not_four_block2
end B686Round5Finite
