import research.tasks.«B686-Four».round4.worker.K5LossFinite

/-! Exact finite extension: generated by generate_contact_finite.py.
Kernel decide checks two strict signs; old ratio monotonicity covers all n. -/
set_option maxRecDepth 200000
set_option maxHeartbeats 6000000
namespace B686Round5Finite
open B686Round4K5Finite

def cutoff0 (d : ℕ) : ℕ :=
  if d = 3636 then 11377 else if d = 4545 then 14222
  else 312981296038 * d / 100000000000 - 3

theorem signs0_3000 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 3000)) <
      product 5 (cutoff0 (t.val + 3000) + (t.val + 3000)) ∧
    product 5 (cutoff0 (t.val + 3000) + 1 + (t.val + 3000)) <
      4 * product 5 (cutoff0 (t.val + 3000) + 1) := by
  decide

theorem signs0_3200 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 3200)) <
      product 5 (cutoff0 (t.val + 3200) + (t.val + 3200)) ∧
    product 5 (cutoff0 (t.val + 3200) + 1 + (t.val + 3200)) <
      4 * product 5 (cutoff0 (t.val + 3200) + 1) := by
  decide

theorem signs0_3400 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 3400)) <
      product 5 (cutoff0 (t.val + 3400) + (t.val + 3400)) ∧
    product 5 (cutoff0 (t.val + 3400) + 1 + (t.val + 3400)) <
      4 * product 5 (cutoff0 (t.val + 3400) + 1) := by
  decide

theorem signs0_3600 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 3600)) <
      product 5 (cutoff0 (t.val + 3600) + (t.val + 3600)) ∧
    product 5 (cutoff0 (t.val + 3600) + 1 + (t.val + 3600)) <
      4 * product 5 (cutoff0 (t.val + 3600) + 1) := by
  decide

theorem signs0_3800 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 3800)) <
      product 5 (cutoff0 (t.val + 3800) + (t.val + 3800)) ∧
    product 5 (cutoff0 (t.val + 3800) + 1 + (t.val + 3800)) <
      4 * product 5 (cutoff0 (t.val + 3800) + 1) := by
  decide

theorem signs0_4000 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 4000)) <
      product 5 (cutoff0 (t.val + 4000) + (t.val + 4000)) ∧
    product 5 (cutoff0 (t.val + 4000) + 1 + (t.val + 4000)) <
      4 * product 5 (cutoff0 (t.val + 4000) + 1) := by
  decide

theorem signs0_4200 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 4200)) <
      product 5 (cutoff0 (t.val + 4200) + (t.val + 4200)) ∧
    product 5 (cutoff0 (t.val + 4200) + 1 + (t.val + 4200)) <
      4 * product 5 (cutoff0 (t.val + 4200) + 1) := by
  decide

theorem signs0_4400 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 4400)) <
      product 5 (cutoff0 (t.val + 4400) + (t.val + 4400)) ∧
    product 5 (cutoff0 (t.val + 4400) + 1 + (t.val + 4400)) <
      4 * product 5 (cutoff0 (t.val + 4400) + 1) := by
  decide

theorem signs0_4600 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 4600)) <
      product 5 (cutoff0 (t.val + 4600) + (t.val + 4600)) ∧
    product 5 (cutoff0 (t.val + 4600) + 1 + (t.val + 4600)) <
      4 * product 5 (cutoff0 (t.val + 4600) + 1) := by
  decide

theorem signs0_4800 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 4800)) <
      product 5 (cutoff0 (t.val + 4800) + (t.val + 4800)) ∧
    product 5 (cutoff0 (t.val + 4800) + 1 + (t.val + 4800)) <
      4 * product 5 (cutoff0 (t.val + 4800) + 1) := by
  decide

theorem signs0_5000 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 5000)) <
      product 5 (cutoff0 (t.val + 5000) + (t.val + 5000)) ∧
    product 5 (cutoff0 (t.val + 5000) + 1 + (t.val + 5000)) <
      4 * product 5 (cutoff0 (t.val + 5000) + 1) := by
  decide

theorem signs0_5200 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 5200)) <
      product 5 (cutoff0 (t.val + 5200) + (t.val + 5200)) ∧
    product 5 (cutoff0 (t.val + 5200) + 1 + (t.val + 5200)) <
      4 * product 5 (cutoff0 (t.val + 5200) + 1) := by
  decide

theorem signs0_5400 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 5400)) <
      product 5 (cutoff0 (t.val + 5400) + (t.val + 5400)) ∧
    product 5 (cutoff0 (t.val + 5400) + 1 + (t.val + 5400)) <
      4 * product 5 (cutoff0 (t.val + 5400) + 1) := by
  decide

theorem signs0_5600 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 5600)) <
      product 5 (cutoff0 (t.val + 5600) + (t.val + 5600)) ∧
    product 5 (cutoff0 (t.val + 5600) + 1 + (t.val + 5600)) <
      4 * product 5 (cutoff0 (t.val + 5600) + 1) := by
  decide

theorem signs0_5800 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 5800)) <
      product 5 (cutoff0 (t.val + 5800) + (t.val + 5800)) ∧
    product 5 (cutoff0 (t.val + 5800) + 1 + (t.val + 5800)) <
      4 * product 5 (cutoff0 (t.val + 5800) + 1) := by
  decide

theorem signs0_6000 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 6000)) <
      product 5 (cutoff0 (t.val + 6000) + (t.val + 6000)) ∧
    product 5 (cutoff0 (t.val + 6000) + 1 + (t.val + 6000)) <
      4 * product 5 (cutoff0 (t.val + 6000) + 1) := by
  decide

theorem signs0_6200 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 6200)) <
      product 5 (cutoff0 (t.val + 6200) + (t.val + 6200)) ∧
    product 5 (cutoff0 (t.val + 6200) + 1 + (t.val + 6200)) <
      4 * product 5 (cutoff0 (t.val + 6200) + 1) := by
  decide

theorem signs0_6400 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 6400)) <
      product 5 (cutoff0 (t.val + 6400) + (t.val + 6400)) ∧
    product 5 (cutoff0 (t.val + 6400) + 1 + (t.val + 6400)) <
      4 * product 5 (cutoff0 (t.val + 6400) + 1) := by
  decide

theorem signs0_6600 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 6600)) <
      product 5 (cutoff0 (t.val + 6600) + (t.val + 6600)) ∧
    product 5 (cutoff0 (t.val + 6600) + 1 + (t.val + 6600)) <
      4 * product 5 (cutoff0 (t.val + 6600) + 1) := by
  decide

theorem signs0_6800 : ∀ t : Fin 200,
    4 * product 5 (cutoff0 (t.val + 6800)) <
      product 5 (cutoff0 (t.val + 6800) + (t.val + 6800)) ∧
    product 5 (cutoff0 (t.val + 6800) + 1 + (t.val + 6800)) <
      4 * product 5 (cutoff0 (t.val + 6800) + 1) := by
  decide

theorem not_four_block0 (n d : ℕ) (hl : 3000 ≤ d) (hu : d < 7000) :
    (∏ r ∈ Finset.Icc 1 (5 : ℕ), (n + d + r)) ≠
      4 * (∏ r ∈ Finset.Icc 1 (5 : ℕ), (n + r)) := by
  by_cases hb3000 : d < 3200
  ·
    have h := signs0_3000 ⟨d - 3000, by omega⟩
    have he : d - 3000 + 3000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb3200 : d < 3400
  ·
    have h := signs0_3200 ⟨d - 3200, by omega⟩
    have he : d - 3200 + 3200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb3400 : d < 3600
  ·
    have h := signs0_3400 ⟨d - 3400, by omega⟩
    have he : d - 3400 + 3400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb3600 : d < 3800
  ·
    have h := signs0_3600 ⟨d - 3600, by omega⟩
    have he : d - 3600 + 3600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb3800 : d < 4000
  ·
    have h := signs0_3800 ⟨d - 3800, by omega⟩
    have he : d - 3800 + 3800 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb4000 : d < 4200
  ·
    have h := signs0_4000 ⟨d - 4000, by omega⟩
    have he : d - 4000 + 4000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb4200 : d < 4400
  ·
    have h := signs0_4200 ⟨d - 4200, by omega⟩
    have he : d - 4200 + 4200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb4400 : d < 4600
  ·
    have h := signs0_4400 ⟨d - 4400, by omega⟩
    have he : d - 4400 + 4400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb4600 : d < 4800
  ·
    have h := signs0_4600 ⟨d - 4600, by omega⟩
    have he : d - 4600 + 4600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb4800 : d < 5000
  ·
    have h := signs0_4800 ⟨d - 4800, by omega⟩
    have he : d - 4800 + 4800 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb5000 : d < 5200
  ·
    have h := signs0_5000 ⟨d - 5000, by omega⟩
    have he : d - 5000 + 5000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb5200 : d < 5400
  ·
    have h := signs0_5200 ⟨d - 5200, by omega⟩
    have he : d - 5200 + 5200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb5400 : d < 5600
  ·
    have h := signs0_5400 ⟨d - 5400, by omega⟩
    have he : d - 5400 + 5400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb5600 : d < 5800
  ·
    have h := signs0_5600 ⟨d - 5600, by omega⟩
    have he : d - 5600 + 5600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb5800 : d < 6000
  ·
    have h := signs0_5800 ⟨d - 5800, by omega⟩
    have he : d - 5800 + 5800 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb6000 : d < 6200
  ·
    have h := signs0_6000 ⟨d - 6000, by omega⟩
    have he : d - 6000 + 6000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb6200 : d < 6400
  ·
    have h := signs0_6200 ⟨d - 6200, by omega⟩
    have he : d - 6200 + 6200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb6400 : d < 6600
  ·
    have h := signs0_6400 ⟨d - 6400, by omega⟩
    have he : d - 6400 + 6400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  by_cases hb6600 : d < 6800
  ·
    have h := signs0_6600 ⟨d - 6600, by omega⟩
    have he : d - 6600 + 6600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2
  have h := signs0_6800 ⟨d - 6800, by omega⟩
  have he : d - 6800 + 6800 = d := by omega
  simp only [he] at h
  exact not_four_of_adjacent_signs 5 d (cutoff0 d) n h.1 h.2

/-- info: 'B686Round5Finite.not_four_block0' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms not_four_block0
end B686Round5Finite
