import research.tasks.«B686-Four».round4.worker.K5LossFinite

/-! Exact finite extension: generated by generate_contact_finite.py.
Kernel decide checks two strict signs; old ratio monotonicity covers all n. -/
set_option maxRecDepth 200000
set_option maxHeartbeats 6000000
namespace B686Round5Finite
open B686Round4K5Finite

def cutoff3 (d : ℕ) : ℕ :=
  if d = 3636 then 11377 else if d = 4545 then 14222
  else 312981296038 * d / 100000000000 - 3

theorem signs3_15000 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 15000)) <
      product 5 (cutoff3 (t.val + 15000) + (t.val + 15000)) ∧
    product 5 (cutoff3 (t.val + 15000) + 1 + (t.val + 15000)) <
      4 * product 5 (cutoff3 (t.val + 15000) + 1) := by
  decide

theorem signs3_15200 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 15200)) <
      product 5 (cutoff3 (t.val + 15200) + (t.val + 15200)) ∧
    product 5 (cutoff3 (t.val + 15200) + 1 + (t.val + 15200)) <
      4 * product 5 (cutoff3 (t.val + 15200) + 1) := by
  decide

theorem signs3_15400 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 15400)) <
      product 5 (cutoff3 (t.val + 15400) + (t.val + 15400)) ∧
    product 5 (cutoff3 (t.val + 15400) + 1 + (t.val + 15400)) <
      4 * product 5 (cutoff3 (t.val + 15400) + 1) := by
  decide

theorem signs3_15600 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 15600)) <
      product 5 (cutoff3 (t.val + 15600) + (t.val + 15600)) ∧
    product 5 (cutoff3 (t.val + 15600) + 1 + (t.val + 15600)) <
      4 * product 5 (cutoff3 (t.val + 15600) + 1) := by
  decide

theorem signs3_15800 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 15800)) <
      product 5 (cutoff3 (t.val + 15800) + (t.val + 15800)) ∧
    product 5 (cutoff3 (t.val + 15800) + 1 + (t.val + 15800)) <
      4 * product 5 (cutoff3 (t.val + 15800) + 1) := by
  decide

theorem signs3_16000 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 16000)) <
      product 5 (cutoff3 (t.val + 16000) + (t.val + 16000)) ∧
    product 5 (cutoff3 (t.val + 16000) + 1 + (t.val + 16000)) <
      4 * product 5 (cutoff3 (t.val + 16000) + 1) := by
  decide

theorem signs3_16200 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 16200)) <
      product 5 (cutoff3 (t.val + 16200) + (t.val + 16200)) ∧
    product 5 (cutoff3 (t.val + 16200) + 1 + (t.val + 16200)) <
      4 * product 5 (cutoff3 (t.val + 16200) + 1) := by
  decide

theorem signs3_16400 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 16400)) <
      product 5 (cutoff3 (t.val + 16400) + (t.val + 16400)) ∧
    product 5 (cutoff3 (t.val + 16400) + 1 + (t.val + 16400)) <
      4 * product 5 (cutoff3 (t.val + 16400) + 1) := by
  decide

theorem signs3_16600 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 16600)) <
      product 5 (cutoff3 (t.val + 16600) + (t.val + 16600)) ∧
    product 5 (cutoff3 (t.val + 16600) + 1 + (t.val + 16600)) <
      4 * product 5 (cutoff3 (t.val + 16600) + 1) := by
  decide

theorem signs3_16800 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 16800)) <
      product 5 (cutoff3 (t.val + 16800) + (t.val + 16800)) ∧
    product 5 (cutoff3 (t.val + 16800) + 1 + (t.val + 16800)) <
      4 * product 5 (cutoff3 (t.val + 16800) + 1) := by
  decide

theorem signs3_17000 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 17000)) <
      product 5 (cutoff3 (t.val + 17000) + (t.val + 17000)) ∧
    product 5 (cutoff3 (t.val + 17000) + 1 + (t.val + 17000)) <
      4 * product 5 (cutoff3 (t.val + 17000) + 1) := by
  decide

theorem signs3_17200 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 17200)) <
      product 5 (cutoff3 (t.val + 17200) + (t.val + 17200)) ∧
    product 5 (cutoff3 (t.val + 17200) + 1 + (t.val + 17200)) <
      4 * product 5 (cutoff3 (t.val + 17200) + 1) := by
  decide

theorem signs3_17400 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 17400)) <
      product 5 (cutoff3 (t.val + 17400) + (t.val + 17400)) ∧
    product 5 (cutoff3 (t.val + 17400) + 1 + (t.val + 17400)) <
      4 * product 5 (cutoff3 (t.val + 17400) + 1) := by
  decide

theorem signs3_17600 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 17600)) <
      product 5 (cutoff3 (t.val + 17600) + (t.val + 17600)) ∧
    product 5 (cutoff3 (t.val + 17600) + 1 + (t.val + 17600)) <
      4 * product 5 (cutoff3 (t.val + 17600) + 1) := by
  decide

theorem signs3_17800 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 17800)) <
      product 5 (cutoff3 (t.val + 17800) + (t.val + 17800)) ∧
    product 5 (cutoff3 (t.val + 17800) + 1 + (t.val + 17800)) <
      4 * product 5 (cutoff3 (t.val + 17800) + 1) := by
  decide

theorem signs3_18000 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 18000)) <
      product 5 (cutoff3 (t.val + 18000) + (t.val + 18000)) ∧
    product 5 (cutoff3 (t.val + 18000) + 1 + (t.val + 18000)) <
      4 * product 5 (cutoff3 (t.val + 18000) + 1) := by
  decide

theorem signs3_18200 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 18200)) <
      product 5 (cutoff3 (t.val + 18200) + (t.val + 18200)) ∧
    product 5 (cutoff3 (t.val + 18200) + 1 + (t.val + 18200)) <
      4 * product 5 (cutoff3 (t.val + 18200) + 1) := by
  decide

theorem signs3_18400 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 18400)) <
      product 5 (cutoff3 (t.val + 18400) + (t.val + 18400)) ∧
    product 5 (cutoff3 (t.val + 18400) + 1 + (t.val + 18400)) <
      4 * product 5 (cutoff3 (t.val + 18400) + 1) := by
  decide

theorem signs3_18600 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 18600)) <
      product 5 (cutoff3 (t.val + 18600) + (t.val + 18600)) ∧
    product 5 (cutoff3 (t.val + 18600) + 1 + (t.val + 18600)) <
      4 * product 5 (cutoff3 (t.val + 18600) + 1) := by
  decide

theorem signs3_18800 : ∀ t : Fin 200,
    4 * product 5 (cutoff3 (t.val + 18800)) <
      product 5 (cutoff3 (t.val + 18800) + (t.val + 18800)) ∧
    product 5 (cutoff3 (t.val + 18800) + 1 + (t.val + 18800)) <
      4 * product 5 (cutoff3 (t.val + 18800) + 1) := by
  decide

theorem not_four_block3 (n d : ℕ) (hl : 15000 ≤ d) (hu : d < 19000) :
    (∏ r ∈ Finset.Icc 1 (5 : ℕ), (n + d + r)) ≠
      4 * (∏ r ∈ Finset.Icc 1 (5 : ℕ), (n + r)) := by
  by_cases hb15000 : d < 15200
  ·
    have h := signs3_15000 ⟨d - 15000, by omega⟩
    have he : d - 15000 + 15000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb15200 : d < 15400
  ·
    have h := signs3_15200 ⟨d - 15200, by omega⟩
    have he : d - 15200 + 15200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb15400 : d < 15600
  ·
    have h := signs3_15400 ⟨d - 15400, by omega⟩
    have he : d - 15400 + 15400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb15600 : d < 15800
  ·
    have h := signs3_15600 ⟨d - 15600, by omega⟩
    have he : d - 15600 + 15600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb15800 : d < 16000
  ·
    have h := signs3_15800 ⟨d - 15800, by omega⟩
    have he : d - 15800 + 15800 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb16000 : d < 16200
  ·
    have h := signs3_16000 ⟨d - 16000, by omega⟩
    have he : d - 16000 + 16000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb16200 : d < 16400
  ·
    have h := signs3_16200 ⟨d - 16200, by omega⟩
    have he : d - 16200 + 16200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb16400 : d < 16600
  ·
    have h := signs3_16400 ⟨d - 16400, by omega⟩
    have he : d - 16400 + 16400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb16600 : d < 16800
  ·
    have h := signs3_16600 ⟨d - 16600, by omega⟩
    have he : d - 16600 + 16600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb16800 : d < 17000
  ·
    have h := signs3_16800 ⟨d - 16800, by omega⟩
    have he : d - 16800 + 16800 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb17000 : d < 17200
  ·
    have h := signs3_17000 ⟨d - 17000, by omega⟩
    have he : d - 17000 + 17000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb17200 : d < 17400
  ·
    have h := signs3_17200 ⟨d - 17200, by omega⟩
    have he : d - 17200 + 17200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb17400 : d < 17600
  ·
    have h := signs3_17400 ⟨d - 17400, by omega⟩
    have he : d - 17400 + 17400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb17600 : d < 17800
  ·
    have h := signs3_17600 ⟨d - 17600, by omega⟩
    have he : d - 17600 + 17600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb17800 : d < 18000
  ·
    have h := signs3_17800 ⟨d - 17800, by omega⟩
    have he : d - 17800 + 17800 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb18000 : d < 18200
  ·
    have h := signs3_18000 ⟨d - 18000, by omega⟩
    have he : d - 18000 + 18000 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb18200 : d < 18400
  ·
    have h := signs3_18200 ⟨d - 18200, by omega⟩
    have he : d - 18200 + 18200 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb18400 : d < 18600
  ·
    have h := signs3_18400 ⟨d - 18400, by omega⟩
    have he : d - 18400 + 18400 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  by_cases hb18600 : d < 18800
  ·
    have h := signs3_18600 ⟨d - 18600, by omega⟩
    have he : d - 18600 + 18600 = d := by omega
    simp only [he] at h
    exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2
  have h := signs3_18800 ⟨d - 18800, by omega⟩
  have he : d - 18800 + 18800 = d := by omega
  simp only [he] at h
  exact not_four_of_adjacent_signs 5 d (cutoff3 d) n h.1 h.2

/-- info: 'B686Round5Finite.not_four_block3' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms not_four_block3
end B686Round5Finite
