-- Candidate only: unified explicit A original-problem consumers.
-- Generated by verification/huan-all-a-plan/generate_huan_all_a.py.
-- Historical 29/35/36/37 remain receipt-pending until their actual
-- receipt roots are supplied; this file does not claim their acceptance.
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row029J2.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row035J2.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row036T.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row037J32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.HuanRecoveredOriginals
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row046B8.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row047B8.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row048B8.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row049B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row050B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row051B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row052B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row053B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row054B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row055B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row056B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row057B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row058B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row059B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row060B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row061B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row062B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row063B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row064B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row065B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row066B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row067B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row068B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row069B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row070B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row071B64.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row072B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row073B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row074B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row075B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row076B16.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row077B16.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row078B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row079B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row080B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row081B16.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row082B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row083B16.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row084B16.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row085B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row086B16.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row087B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row088B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row089B16.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row090B16.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row091B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row092B16.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row093B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row094B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row095B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row096B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row097B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row098B16.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row099B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row100B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row101B16.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row102B16.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row103B16.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row104B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row105B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row106B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row107B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row108B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row109B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row110B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row111B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row112B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row113B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row114B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row115B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row116B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row117B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row118B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row119B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row120B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row121B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row122B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row123B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row124B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row125B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row126B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row127B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row128B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row129B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row130B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row131B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row132B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row133B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row134B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row135B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row136B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row137B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row138B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row139B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row140B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row141B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row142B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row143B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row144B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row145B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row146B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row147B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row148B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row149B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row150B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row151B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row152B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row153B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row154B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row155B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row156B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row157B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row158B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row159B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row160B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row161B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row162B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row163B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row164B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row165B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row166B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row167B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row168B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row169B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row170B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row171B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row172B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row173B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row174B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row175B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row176B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row177B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row178B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row179B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row180B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row181B16.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row182B8.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row183B32.Original
import research.tasks.«B699-Binomial».runs.«20260911-low-index-lean-513dc7cc».lean.rows.Row184B32.Original

set_option maxRecDepth 4096
set_option exponentiation.threshold 1000000

namespace B699LowIndex.LowIndexLean513dc7cc.HuanAllA

theorem original_i029 :
    ∀ n j : ℕ, 1 ≤ 29 ∧ 29 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 29 ≤ p ∧ p ∣ Nat.choose n 29 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i029

theorem original_i035 :
    ∀ n j : ℕ, 1 ≤ 35 ∧ 35 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 35 ≤ p ∧ p ∣ Nat.choose n 35 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i035

theorem original_i036 :
    ∀ n j : ℕ, 1 ≤ 36 ∧ 36 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 36 ≤ p ∧ p ∣ Nat.choose n 36 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i036

theorem original_i037 :
    ∀ n j : ℕ, 1 ≤ 37 ∧ 37 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 37 ≤ p ∧ p ∣ Nat.choose n 37 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i037

theorem original_i038 :
    ∀ n j : ℕ, 1 ≤ 38 ∧ 38 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 38 ≤ p ∧ p ∣ Nat.choose n 38 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.HuanRecovery.original_i038

theorem original_i039 :
    ∀ n j : ℕ, 1 ≤ 39 ∧ 39 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 39 ≤ p ∧ p ∣ Nat.choose n 39 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.HuanRecovery.original_i039

theorem original_i040 :
    ∀ n j : ℕ, 1 ≤ 40 ∧ 40 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 40 ≤ p ∧ p ∣ Nat.choose n 40 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.HuanRecovery.original_i040

theorem original_i041 :
    ∀ n j : ℕ, 1 ≤ 41 ∧ 41 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 41 ≤ p ∧ p ∣ Nat.choose n 41 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.HuanRecovery.original_i041

theorem original_i042 :
    ∀ n j : ℕ, 1 ≤ 42 ∧ 42 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 42 ≤ p ∧ p ∣ Nat.choose n 42 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.HuanRecovery.original_i042

theorem original_i043 :
    ∀ n j : ℕ, 1 ≤ 43 ∧ 43 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 43 ≤ p ∧ p ∣ Nat.choose n 43 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.HuanRecovery.original_i043

theorem original_i044 :
    ∀ n j : ℕ, 1 ≤ 44 ∧ 44 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 44 ≤ p ∧ p ∣ Nat.choose n 44 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.HuanRecovery.original_i044

theorem original_i045 :
    ∀ n j : ℕ, 1 ≤ 45 ∧ 45 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 45 ≤ p ∧ p ∣ Nat.choose n 45 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.HuanRecovery.original_i045

theorem original_i046 :
    ∀ n j : ℕ, 1 ≤ 46 ∧ 46 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 46 ≤ p ∧ p ∣ Nat.choose n 46 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i046

theorem original_i047 :
    ∀ n j : ℕ, 1 ≤ 47 ∧ 47 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 47 ≤ p ∧ p ∣ Nat.choose n 47 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i047

theorem original_i048 :
    ∀ n j : ℕ, 1 ≤ 48 ∧ 48 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 48 ≤ p ∧ p ∣ Nat.choose n 48 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i048

theorem original_i049 :
    ∀ n j : ℕ, 1 ≤ 49 ∧ 49 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 49 ≤ p ∧ p ∣ Nat.choose n 49 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i049

theorem original_i050 :
    ∀ n j : ℕ, 1 ≤ 50 ∧ 50 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 50 ≤ p ∧ p ∣ Nat.choose n 50 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i050

theorem original_i051 :
    ∀ n j : ℕ, 1 ≤ 51 ∧ 51 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 51 ≤ p ∧ p ∣ Nat.choose n 51 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i051

theorem original_i052 :
    ∀ n j : ℕ, 1 ≤ 52 ∧ 52 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 52 ≤ p ∧ p ∣ Nat.choose n 52 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i052

theorem original_i053 :
    ∀ n j : ℕ, 1 ≤ 53 ∧ 53 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 53 ≤ p ∧ p ∣ Nat.choose n 53 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i053

theorem original_i054 :
    ∀ n j : ℕ, 1 ≤ 54 ∧ 54 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 54 ≤ p ∧ p ∣ Nat.choose n 54 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i054

theorem original_i055 :
    ∀ n j : ℕ, 1 ≤ 55 ∧ 55 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 55 ≤ p ∧ p ∣ Nat.choose n 55 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i055

theorem original_i056 :
    ∀ n j : ℕ, 1 ≤ 56 ∧ 56 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 56 ≤ p ∧ p ∣ Nat.choose n 56 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i056

theorem original_i057 :
    ∀ n j : ℕ, 1 ≤ 57 ∧ 57 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 57 ≤ p ∧ p ∣ Nat.choose n 57 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i057

theorem original_i058 :
    ∀ n j : ℕ, 1 ≤ 58 ∧ 58 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 58 ≤ p ∧ p ∣ Nat.choose n 58 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i058

theorem original_i059 :
    ∀ n j : ℕ, 1 ≤ 59 ∧ 59 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 59 ≤ p ∧ p ∣ Nat.choose n 59 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i059

theorem original_i060 :
    ∀ n j : ℕ, 1 ≤ 60 ∧ 60 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 60 ≤ p ∧ p ∣ Nat.choose n 60 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i060

theorem original_i061 :
    ∀ n j : ℕ, 1 ≤ 61 ∧ 61 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 61 ≤ p ∧ p ∣ Nat.choose n 61 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i061

theorem original_i062 :
    ∀ n j : ℕ, 1 ≤ 62 ∧ 62 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 62 ≤ p ∧ p ∣ Nat.choose n 62 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i062

theorem original_i063 :
    ∀ n j : ℕ, 1 ≤ 63 ∧ 63 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 63 ≤ p ∧ p ∣ Nat.choose n 63 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i063

theorem original_i064 :
    ∀ n j : ℕ, 1 ≤ 64 ∧ 64 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 64 ≤ p ∧ p ∣ Nat.choose n 64 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i064

theorem original_i065 :
    ∀ n j : ℕ, 1 ≤ 65 ∧ 65 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 65 ≤ p ∧ p ∣ Nat.choose n 65 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i065

theorem original_i066 :
    ∀ n j : ℕ, 1 ≤ 66 ∧ 66 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 66 ≤ p ∧ p ∣ Nat.choose n 66 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i066

theorem original_i067 :
    ∀ n j : ℕ, 1 ≤ 67 ∧ 67 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 67 ≤ p ∧ p ∣ Nat.choose n 67 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i067

theorem original_i068 :
    ∀ n j : ℕ, 1 ≤ 68 ∧ 68 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 68 ≤ p ∧ p ∣ Nat.choose n 68 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i068

theorem original_i069 :
    ∀ n j : ℕ, 1 ≤ 69 ∧ 69 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 69 ≤ p ∧ p ∣ Nat.choose n 69 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i069

theorem original_i070 :
    ∀ n j : ℕ, 1 ≤ 70 ∧ 70 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 70 ≤ p ∧ p ∣ Nat.choose n 70 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i070

theorem original_i071 :
    ∀ n j : ℕ, 1 ≤ 71 ∧ 71 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 71 ≤ p ∧ p ∣ Nat.choose n 71 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i071

theorem original_i072 :
    ∀ n j : ℕ, 1 ≤ 72 ∧ 72 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 72 ≤ p ∧ p ∣ Nat.choose n 72 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i072

theorem original_i073 :
    ∀ n j : ℕ, 1 ≤ 73 ∧ 73 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 73 ≤ p ∧ p ∣ Nat.choose n 73 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i073

theorem original_i074 :
    ∀ n j : ℕ, 1 ≤ 74 ∧ 74 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 74 ≤ p ∧ p ∣ Nat.choose n 74 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i074

theorem original_i075 :
    ∀ n j : ℕ, 1 ≤ 75 ∧ 75 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 75 ≤ p ∧ p ∣ Nat.choose n 75 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i075

theorem original_i076 :
    ∀ n j : ℕ, 1 ≤ 76 ∧ 76 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 76 ≤ p ∧ p ∣ Nat.choose n 76 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i076

theorem original_i077 :
    ∀ n j : ℕ, 1 ≤ 77 ∧ 77 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 77 ≤ p ∧ p ∣ Nat.choose n 77 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i077

theorem original_i078 :
    ∀ n j : ℕ, 1 ≤ 78 ∧ 78 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 78 ≤ p ∧ p ∣ Nat.choose n 78 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i078

theorem original_i079 :
    ∀ n j : ℕ, 1 ≤ 79 ∧ 79 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 79 ≤ p ∧ p ∣ Nat.choose n 79 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i079

theorem original_i080 :
    ∀ n j : ℕ, 1 ≤ 80 ∧ 80 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 80 ≤ p ∧ p ∣ Nat.choose n 80 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i080

theorem original_i081 :
    ∀ n j : ℕ, 1 ≤ 81 ∧ 81 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 81 ≤ p ∧ p ∣ Nat.choose n 81 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i081

theorem original_i082 :
    ∀ n j : ℕ, 1 ≤ 82 ∧ 82 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 82 ≤ p ∧ p ∣ Nat.choose n 82 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i082

theorem original_i083 :
    ∀ n j : ℕ, 1 ≤ 83 ∧ 83 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 83 ≤ p ∧ p ∣ Nat.choose n 83 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i083

theorem original_i084 :
    ∀ n j : ℕ, 1 ≤ 84 ∧ 84 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 84 ≤ p ∧ p ∣ Nat.choose n 84 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i084

theorem original_i085 :
    ∀ n j : ℕ, 1 ≤ 85 ∧ 85 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 85 ≤ p ∧ p ∣ Nat.choose n 85 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i085

theorem original_i086 :
    ∀ n j : ℕ, 1 ≤ 86 ∧ 86 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 86 ≤ p ∧ p ∣ Nat.choose n 86 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i086

theorem original_i087 :
    ∀ n j : ℕ, 1 ≤ 87 ∧ 87 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 87 ≤ p ∧ p ∣ Nat.choose n 87 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i087

theorem original_i088 :
    ∀ n j : ℕ, 1 ≤ 88 ∧ 88 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 88 ≤ p ∧ p ∣ Nat.choose n 88 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i088

theorem original_i089 :
    ∀ n j : ℕ, 1 ≤ 89 ∧ 89 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 89 ≤ p ∧ p ∣ Nat.choose n 89 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i089

theorem original_i090 :
    ∀ n j : ℕ, 1 ≤ 90 ∧ 90 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 90 ≤ p ∧ p ∣ Nat.choose n 90 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i090

theorem original_i091 :
    ∀ n j : ℕ, 1 ≤ 91 ∧ 91 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 91 ≤ p ∧ p ∣ Nat.choose n 91 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i091

theorem original_i092 :
    ∀ n j : ℕ, 1 ≤ 92 ∧ 92 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 92 ≤ p ∧ p ∣ Nat.choose n 92 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i092

theorem original_i093 :
    ∀ n j : ℕ, 1 ≤ 93 ∧ 93 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 93 ≤ p ∧ p ∣ Nat.choose n 93 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i093

theorem original_i094 :
    ∀ n j : ℕ, 1 ≤ 94 ∧ 94 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 94 ≤ p ∧ p ∣ Nat.choose n 94 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i094

theorem original_i095 :
    ∀ n j : ℕ, 1 ≤ 95 ∧ 95 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 95 ≤ p ∧ p ∣ Nat.choose n 95 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i095

theorem original_i096 :
    ∀ n j : ℕ, 1 ≤ 96 ∧ 96 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 96 ≤ p ∧ p ∣ Nat.choose n 96 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i096

theorem original_i097 :
    ∀ n j : ℕ, 1 ≤ 97 ∧ 97 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 97 ≤ p ∧ p ∣ Nat.choose n 97 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i097

theorem original_i098 :
    ∀ n j : ℕ, 1 ≤ 98 ∧ 98 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 98 ≤ p ∧ p ∣ Nat.choose n 98 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i098

theorem original_i099 :
    ∀ n j : ℕ, 1 ≤ 99 ∧ 99 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 99 ≤ p ∧ p ∣ Nat.choose n 99 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i099

theorem original_i100 :
    ∀ n j : ℕ, 1 ≤ 100 ∧ 100 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 100 ≤ p ∧ p ∣ Nat.choose n 100 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i100

theorem original_i101 :
    ∀ n j : ℕ, 1 ≤ 101 ∧ 101 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 101 ≤ p ∧ p ∣ Nat.choose n 101 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i101

theorem original_i102 :
    ∀ n j : ℕ, 1 ≤ 102 ∧ 102 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 102 ≤ p ∧ p ∣ Nat.choose n 102 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i102

theorem original_i103 :
    ∀ n j : ℕ, 1 ≤ 103 ∧ 103 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 103 ≤ p ∧ p ∣ Nat.choose n 103 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i103

theorem original_i104 :
    ∀ n j : ℕ, 1 ≤ 104 ∧ 104 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 104 ≤ p ∧ p ∣ Nat.choose n 104 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i104

theorem original_i105 :
    ∀ n j : ℕ, 1 ≤ 105 ∧ 105 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 105 ≤ p ∧ p ∣ Nat.choose n 105 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i105

theorem original_i106 :
    ∀ n j : ℕ, 1 ≤ 106 ∧ 106 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 106 ≤ p ∧ p ∣ Nat.choose n 106 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i106

theorem original_i107 :
    ∀ n j : ℕ, 1 ≤ 107 ∧ 107 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 107 ≤ p ∧ p ∣ Nat.choose n 107 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i107

theorem original_i108 :
    ∀ n j : ℕ, 1 ≤ 108 ∧ 108 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 108 ≤ p ∧ p ∣ Nat.choose n 108 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i108

theorem original_i109 :
    ∀ n j : ℕ, 1 ≤ 109 ∧ 109 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 109 ≤ p ∧ p ∣ Nat.choose n 109 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i109

theorem original_i110 :
    ∀ n j : ℕ, 1 ≤ 110 ∧ 110 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 110 ≤ p ∧ p ∣ Nat.choose n 110 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i110

theorem original_i111 :
    ∀ n j : ℕ, 1 ≤ 111 ∧ 111 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 111 ≤ p ∧ p ∣ Nat.choose n 111 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i111

theorem original_i112 :
    ∀ n j : ℕ, 1 ≤ 112 ∧ 112 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 112 ≤ p ∧ p ∣ Nat.choose n 112 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i112

theorem original_i113 :
    ∀ n j : ℕ, 1 ≤ 113 ∧ 113 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 113 ≤ p ∧ p ∣ Nat.choose n 113 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i113

theorem original_i114 :
    ∀ n j : ℕ, 1 ≤ 114 ∧ 114 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 114 ≤ p ∧ p ∣ Nat.choose n 114 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i114

theorem original_i115 :
    ∀ n j : ℕ, 1 ≤ 115 ∧ 115 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 115 ≤ p ∧ p ∣ Nat.choose n 115 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i115

theorem original_i116 :
    ∀ n j : ℕ, 1 ≤ 116 ∧ 116 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 116 ≤ p ∧ p ∣ Nat.choose n 116 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i116

theorem original_i117 :
    ∀ n j : ℕ, 1 ≤ 117 ∧ 117 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 117 ≤ p ∧ p ∣ Nat.choose n 117 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i117

theorem original_i118 :
    ∀ n j : ℕ, 1 ≤ 118 ∧ 118 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 118 ≤ p ∧ p ∣ Nat.choose n 118 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i118

theorem original_i119 :
    ∀ n j : ℕ, 1 ≤ 119 ∧ 119 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 119 ≤ p ∧ p ∣ Nat.choose n 119 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i119

theorem original_i120 :
    ∀ n j : ℕ, 1 ≤ 120 ∧ 120 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 120 ≤ p ∧ p ∣ Nat.choose n 120 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i120

theorem original_i121 :
    ∀ n j : ℕ, 1 ≤ 121 ∧ 121 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 121 ≤ p ∧ p ∣ Nat.choose n 121 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i121

theorem original_i122 :
    ∀ n j : ℕ, 1 ≤ 122 ∧ 122 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 122 ≤ p ∧ p ∣ Nat.choose n 122 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i122

theorem original_i123 :
    ∀ n j : ℕ, 1 ≤ 123 ∧ 123 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 123 ≤ p ∧ p ∣ Nat.choose n 123 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i123

theorem original_i124 :
    ∀ n j : ℕ, 1 ≤ 124 ∧ 124 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 124 ≤ p ∧ p ∣ Nat.choose n 124 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i124

theorem original_i125 :
    ∀ n j : ℕ, 1 ≤ 125 ∧ 125 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 125 ≤ p ∧ p ∣ Nat.choose n 125 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i125

theorem original_i126 :
    ∀ n j : ℕ, 1 ≤ 126 ∧ 126 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 126 ≤ p ∧ p ∣ Nat.choose n 126 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i126

theorem original_i127 :
    ∀ n j : ℕ, 1 ≤ 127 ∧ 127 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 127 ≤ p ∧ p ∣ Nat.choose n 127 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i127

theorem original_i128 :
    ∀ n j : ℕ, 1 ≤ 128 ∧ 128 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 128 ≤ p ∧ p ∣ Nat.choose n 128 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i128

theorem original_i129 :
    ∀ n j : ℕ, 1 ≤ 129 ∧ 129 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 129 ≤ p ∧ p ∣ Nat.choose n 129 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i129

theorem original_i130 :
    ∀ n j : ℕ, 1 ≤ 130 ∧ 130 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 130 ≤ p ∧ p ∣ Nat.choose n 130 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i130

theorem original_i131 :
    ∀ n j : ℕ, 1 ≤ 131 ∧ 131 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 131 ≤ p ∧ p ∣ Nat.choose n 131 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i131

theorem original_i132 :
    ∀ n j : ℕ, 1 ≤ 132 ∧ 132 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 132 ≤ p ∧ p ∣ Nat.choose n 132 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i132

theorem original_i133 :
    ∀ n j : ℕ, 1 ≤ 133 ∧ 133 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 133 ≤ p ∧ p ∣ Nat.choose n 133 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i133

theorem original_i134 :
    ∀ n j : ℕ, 1 ≤ 134 ∧ 134 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 134 ≤ p ∧ p ∣ Nat.choose n 134 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i134

theorem original_i135 :
    ∀ n j : ℕ, 1 ≤ 135 ∧ 135 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 135 ≤ p ∧ p ∣ Nat.choose n 135 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i135

theorem original_i136 :
    ∀ n j : ℕ, 1 ≤ 136 ∧ 136 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 136 ≤ p ∧ p ∣ Nat.choose n 136 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i136

theorem original_i137 :
    ∀ n j : ℕ, 1 ≤ 137 ∧ 137 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 137 ≤ p ∧ p ∣ Nat.choose n 137 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i137

theorem original_i138 :
    ∀ n j : ℕ, 1 ≤ 138 ∧ 138 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 138 ≤ p ∧ p ∣ Nat.choose n 138 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i138

theorem original_i139 :
    ∀ n j : ℕ, 1 ≤ 139 ∧ 139 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 139 ≤ p ∧ p ∣ Nat.choose n 139 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i139

theorem original_i140 :
    ∀ n j : ℕ, 1 ≤ 140 ∧ 140 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 140 ≤ p ∧ p ∣ Nat.choose n 140 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i140

theorem original_i141 :
    ∀ n j : ℕ, 1 ≤ 141 ∧ 141 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 141 ≤ p ∧ p ∣ Nat.choose n 141 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i141

theorem original_i142 :
    ∀ n j : ℕ, 1 ≤ 142 ∧ 142 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 142 ≤ p ∧ p ∣ Nat.choose n 142 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i142

theorem original_i143 :
    ∀ n j : ℕ, 1 ≤ 143 ∧ 143 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 143 ≤ p ∧ p ∣ Nat.choose n 143 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i143

theorem original_i144 :
    ∀ n j : ℕ, 1 ≤ 144 ∧ 144 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 144 ≤ p ∧ p ∣ Nat.choose n 144 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i144

theorem original_i145 :
    ∀ n j : ℕ, 1 ≤ 145 ∧ 145 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 145 ≤ p ∧ p ∣ Nat.choose n 145 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i145

theorem original_i146 :
    ∀ n j : ℕ, 1 ≤ 146 ∧ 146 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 146 ≤ p ∧ p ∣ Nat.choose n 146 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i146

theorem original_i147 :
    ∀ n j : ℕ, 1 ≤ 147 ∧ 147 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 147 ≤ p ∧ p ∣ Nat.choose n 147 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i147

theorem original_i148 :
    ∀ n j : ℕ, 1 ≤ 148 ∧ 148 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 148 ≤ p ∧ p ∣ Nat.choose n 148 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i148

theorem original_i149 :
    ∀ n j : ℕ, 1 ≤ 149 ∧ 149 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 149 ≤ p ∧ p ∣ Nat.choose n 149 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i149

theorem original_i150 :
    ∀ n j : ℕ, 1 ≤ 150 ∧ 150 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 150 ≤ p ∧ p ∣ Nat.choose n 150 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i150

theorem original_i151 :
    ∀ n j : ℕ, 1 ≤ 151 ∧ 151 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 151 ≤ p ∧ p ∣ Nat.choose n 151 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i151

theorem original_i152 :
    ∀ n j : ℕ, 1 ≤ 152 ∧ 152 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 152 ≤ p ∧ p ∣ Nat.choose n 152 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i152

theorem original_i153 :
    ∀ n j : ℕ, 1 ≤ 153 ∧ 153 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 153 ≤ p ∧ p ∣ Nat.choose n 153 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i153

theorem original_i154 :
    ∀ n j : ℕ, 1 ≤ 154 ∧ 154 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 154 ≤ p ∧ p ∣ Nat.choose n 154 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i154

theorem original_i155 :
    ∀ n j : ℕ, 1 ≤ 155 ∧ 155 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 155 ≤ p ∧ p ∣ Nat.choose n 155 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i155

theorem original_i156 :
    ∀ n j : ℕ, 1 ≤ 156 ∧ 156 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 156 ≤ p ∧ p ∣ Nat.choose n 156 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i156

theorem original_i157 :
    ∀ n j : ℕ, 1 ≤ 157 ∧ 157 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 157 ≤ p ∧ p ∣ Nat.choose n 157 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i157

theorem original_i158 :
    ∀ n j : ℕ, 1 ≤ 158 ∧ 158 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 158 ≤ p ∧ p ∣ Nat.choose n 158 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i158

theorem original_i159 :
    ∀ n j : ℕ, 1 ≤ 159 ∧ 159 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 159 ≤ p ∧ p ∣ Nat.choose n 159 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i159

theorem original_i160 :
    ∀ n j : ℕ, 1 ≤ 160 ∧ 160 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 160 ≤ p ∧ p ∣ Nat.choose n 160 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i160

theorem original_i161 :
    ∀ n j : ℕ, 1 ≤ 161 ∧ 161 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 161 ≤ p ∧ p ∣ Nat.choose n 161 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i161

theorem original_i162 :
    ∀ n j : ℕ, 1 ≤ 162 ∧ 162 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 162 ≤ p ∧ p ∣ Nat.choose n 162 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i162

theorem original_i163 :
    ∀ n j : ℕ, 1 ≤ 163 ∧ 163 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 163 ≤ p ∧ p ∣ Nat.choose n 163 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i163

theorem original_i164 :
    ∀ n j : ℕ, 1 ≤ 164 ∧ 164 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 164 ≤ p ∧ p ∣ Nat.choose n 164 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i164

theorem original_i165 :
    ∀ n j : ℕ, 1 ≤ 165 ∧ 165 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 165 ≤ p ∧ p ∣ Nat.choose n 165 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i165

theorem original_i166 :
    ∀ n j : ℕ, 1 ≤ 166 ∧ 166 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 166 ≤ p ∧ p ∣ Nat.choose n 166 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i166

theorem original_i167 :
    ∀ n j : ℕ, 1 ≤ 167 ∧ 167 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 167 ≤ p ∧ p ∣ Nat.choose n 167 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i167

theorem original_i168 :
    ∀ n j : ℕ, 1 ≤ 168 ∧ 168 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 168 ≤ p ∧ p ∣ Nat.choose n 168 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i168

theorem original_i169 :
    ∀ n j : ℕ, 1 ≤ 169 ∧ 169 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 169 ≤ p ∧ p ∣ Nat.choose n 169 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i169

theorem original_i170 :
    ∀ n j : ℕ, 1 ≤ 170 ∧ 170 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 170 ≤ p ∧ p ∣ Nat.choose n 170 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i170

theorem original_i171 :
    ∀ n j : ℕ, 1 ≤ 171 ∧ 171 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 171 ≤ p ∧ p ∣ Nat.choose n 171 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i171

theorem original_i172 :
    ∀ n j : ℕ, 1 ≤ 172 ∧ 172 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 172 ≤ p ∧ p ∣ Nat.choose n 172 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i172

theorem original_i173 :
    ∀ n j : ℕ, 1 ≤ 173 ∧ 173 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 173 ≤ p ∧ p ∣ Nat.choose n 173 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i173

theorem original_i174 :
    ∀ n j : ℕ, 1 ≤ 174 ∧ 174 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 174 ≤ p ∧ p ∣ Nat.choose n 174 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i174

theorem original_i175 :
    ∀ n j : ℕ, 1 ≤ 175 ∧ 175 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 175 ≤ p ∧ p ∣ Nat.choose n 175 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i175

theorem original_i176 :
    ∀ n j : ℕ, 1 ≤ 176 ∧ 176 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 176 ≤ p ∧ p ∣ Nat.choose n 176 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i176

theorem original_i177 :
    ∀ n j : ℕ, 1 ≤ 177 ∧ 177 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 177 ≤ p ∧ p ∣ Nat.choose n 177 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i177

theorem original_i178 :
    ∀ n j : ℕ, 1 ≤ 178 ∧ 178 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 178 ≤ p ∧ p ∣ Nat.choose n 178 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i178

theorem original_i179 :
    ∀ n j : ℕ, 1 ≤ 179 ∧ 179 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 179 ≤ p ∧ p ∣ Nat.choose n 179 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i179

theorem original_i180 :
    ∀ n j : ℕ, 1 ≤ 180 ∧ 180 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 180 ≤ p ∧ p ∣ Nat.choose n 180 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i180

theorem original_i181 :
    ∀ n j : ℕ, 1 ≤ 181 ∧ 181 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 181 ≤ p ∧ p ∣ Nat.choose n 181 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i181

theorem original_i182 :
    ∀ n j : ℕ, 1 ≤ 182 ∧ 182 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 182 ≤ p ∧ p ∣ Nat.choose n 182 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i182

theorem original_i183 :
    ∀ n j : ℕ, 1 ≤ 183 ∧ 183 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 183 ≤ p ∧ p ∣ Nat.choose n 183 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i183

theorem original_i184 :
    ∀ n j : ℕ, 1 ≤ 184 ∧ 184 < j ∧ j ≤ n / 2 →
      ∃ p : ℕ, p.Prime ∧ 184 ≤ p ∧ p ∣ Nat.choose n 184 ∧ p ∣ Nat.choose n j :=
  B699LowIndex.LowIndexLean513dc7cc.common_i184

end B699LowIndex.LowIndexLean513dc7cc.HuanAllA

#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i029
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i035
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i036
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i037
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i038
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i039
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i040
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i041
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i042
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i043
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i044
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i045
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i046
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i047
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i048
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i049
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i050
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i051
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i052
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i053
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i054
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i055
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i056
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i057
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i058
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i059
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i060
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i061
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i062
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i063
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i064
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i065
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i066
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i067
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i068
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i069
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i070
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i071
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i072
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i073
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i074
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i075
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i076
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i077
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i078
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i079
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i080
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i081
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i082
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i083
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i084
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i085
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i086
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i087
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i088
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i089
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i090
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i091
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i092
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i093
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i094
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i095
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i096
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i097
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i098
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i099
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i100
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i101
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i102
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i103
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i104
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i105
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i106
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i107
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i108
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i109
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i110
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i111
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i112
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i113
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i114
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i115
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i116
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i117
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i118
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i119
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i120
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i121
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i122
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i123
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i124
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i125
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i126
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i127
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i128
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i129
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i130
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i131
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i132
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i133
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i134
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i135
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i136
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i137
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i138
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i139
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i140
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i141
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i142
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i143
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i144
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i145
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i146
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i147
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i148
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i149
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i150
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i151
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i152
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i153
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i154
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i155
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i156
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i157
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i158
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i159
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i160
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i161
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i162
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i163
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i164
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i165
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i166
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i167
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i168
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i169
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i170
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i171
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i172
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i173
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i174
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i175
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i176
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i177
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i178
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i179
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i180
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i181
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i182
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i183
#print axioms B699LowIndex.LowIndexLean513dc7cc.HuanAllA.original_i184
