"""Exact adjacent signs for the loss-nine tail: 600 <= d < 3000.

The output Lean module checks signs with kernel decide. Python is only a
certificate generator, with independent comb and raw-product arithmetic.
"""
from datetime import datetime, timezone
from math import comb, prod
from pathlib import Path
import json

HERE = Path(__file__).resolve().parent


def main():
    rows = []
    for d in range(600, 3000):
        def f(n):
            return 120 * (comb(n + d + 5, 5) - 4 * comb(n + 5, 5))
        lo, hi = 0, 4 * d
        assert f(lo) > 0 and f(hi) < 0
        while hi - lo > 1:
            mid = (lo + hi) // 2
            if f(mid) > 0:
                lo = mid
            else:
                hi = mid
        assert f(lo) > 0 and f(hi) < 0
        for n in (lo, hi):
            assert f(n) == prod(range(n+d+1, n+d+6)) - 4*prod(range(n+1, n+6))
        rows.append(dict(d=d, cutoff=lo, F_lo=f(lo), F_hi=f(hi)))
    cuts = [r['cutoff'] for r in rows]
    # A compact formula matches every generated cutoff in this precise range.
    # It is not assumed as a formula for the root: Lean still checks both signs.
    assert all(3129813*r['d']//1000000-3 == r['cutoff'] for r in rows)
    blocks = []
    for start in range(600, 3000, 200):
        blocks.append(f'''theorem loss_sign_{start} : ∀ t : Fin 200,
    4 * product 5 (lossCutoff (t.val + {start})) <
      product 5 (lossCutoff (t.val + {start}) + (t.val + {start})) ∧
    product 5 (lossCutoff (t.val + {start}) + 1 + (t.val + {start})) <
      4 * product 5 (lossCutoff (t.val + {start}) + 1) := by
  decide
''')
    assembly = ['  intro d hd', '  obtain ⟨hl, hu⟩ := Finset.mem_Icc.mp hd']
    for start in range(600, 3000, 200):
        if start < 2800:
            assembly += [f'  by_cases h{start} : d < {start+200}', '  ·']
            indent = '    '
        else:
            indent = '  '
        assembly += [indent+f'have h := loss_sign_{start} ⟨d - {start}, by omega⟩',
                     indent+f'have he : d - {start} + {start} = d := by omega',
                     indent+'simpa only [he] using h']
    source = '''import research.tasks.«B686-Four».round4.worker.K5Finite

/-! Exact finite continuation for the loss-nine two-position tail.
All natural n, and precisely 600<=d<3000. Generated by
generate_k5_loss_finite.py; signs are checked by kernel decide. -/

set_option maxRecDepth 200000
set_option maxHeartbeats 4000000

namespace B686Round4K5Finite

def lossCutoff (d : ℕ) : ℕ := 3129813 * d / 1000000 - 3

''' + '\n'.join(blocks) + '''

theorem loss_sign_certificates : ∀ d ∈ Finset.Icc 600 2999,
    4 * product 5 (lossCutoff d) < product 5 (lossCutoff d + d) ∧
      product 5 (lossCutoff d + 1 + d) < 4 * product 5 (lossCutoff d + 1) := by
''' + '\n'.join(assembly) + '''

theorem not_four_loss_finite (n d : ℕ) (hd : 5 ≤ d) (hd' : d < 3000) :
    (∏ r ∈ Finset.Icc 1 (5 : ℕ), (n + d + r)) ≠
      4 * (∏ r ∈ Finset.Icc 1 (5 : ℕ), (n + r)) := by
  by_cases hsmall : d < 600
  · exact not_four_small_displacement n d hd hsmall
  · obtain ⟨hl, hu⟩ := loss_sign_certificates d (Finset.mem_Icc.mpr ⟨by omega, by omega⟩)
    exact not_four_of_adjacent_signs 5 d (lossCutoff d) n hl hu

/-- info: 'B686Round4K5Finite.loss_sign_certificates' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms loss_sign_certificates
/-- info: 'B686Round4K5Finite.not_four_loss_finite' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms not_four_loss_finite

end B686Round4K5Finite
'''
    (HERE / 'K5LossFinite.lean').write_text(source)
    out = dict(utc=datetime.now(timezone.utc).isoformat(),
               evidence='exact computation; Lean kernel certificate is separate',
               scope='k5, 600<=d<3000; all natural n by adjacent-sign ratio monotonicity',
               gap_margins=dict(lower=9*8387**2-633*1000**2,
                                upper=634*1000**2-9*8392**2), rows=rows)
    assert min(out['gap_margins'].values()) > 0
    (HERE / 'k5-loss-finite-certificates.json').write_text(json.dumps(out, indent=2)+'\n')
    print(json.dumps(dict(rows=len(rows), max_cutoff=cuts[-1], gaps=out['gap_margins'])))


if __name__ == '__main__':
    main()
