import research.tasks.«B686-Four».round4.worker.K5Finite

/-! Exact finite continuation for the loss-nine two-position tail.
All natural n, and precisely 600<=d<3000. Generated by
generate_k5_loss_finite.py; signs are checked by kernel decide. -/

set_option maxRecDepth 200000
set_option maxHeartbeats 4000000

namespace B686Round4K5Finite

def lossCutoff (d : ℕ) : ℕ := 3129813 * d / 1000000 - 3

theorem loss_sign_600 : ∀ t : Fin 200,
    4 * product 5 (lossCutoff (t.val + 600)) <
      product 5 (lossCutoff (t.val + 600) + (t.val + 600)) ∧
    product 5 (lossCutoff (t.val + 600) + 1 + (t.val + 600)) <
      4 * product 5 (lossCutoff (t.val + 600) + 1) := by
  decide

theorem loss_sign_800 : ∀ t : Fin 200,
    4 * product 5 (lossCutoff (t.val + 800)) <
      product 5 (lossCutoff (t.val + 800) + (t.val + 800)) ∧
    product 5 (lossCutoff (t.val + 800) + 1 + (t.val + 800)) <
      4 * product 5 (lossCutoff (t.val + 800) + 1) := by
  decide

theorem loss_sign_1000 : ∀ t : Fin 200,
    4 * product 5 (lossCutoff (t.val + 1000)) <
      product 5 (lossCutoff (t.val + 1000) + (t.val + 1000)) ∧
    product 5 (lossCutoff (t.val + 1000) + 1 + (t.val + 1000)) <
      4 * product 5 (lossCutoff (t.val + 1000) + 1) := by
  decide

theorem loss_sign_1200 : ∀ t : Fin 200,
    4 * product 5 (lossCutoff (t.val + 1200)) <
      product 5 (lossCutoff (t.val + 1200) + (t.val + 1200)) ∧
    product 5 (lossCutoff (t.val + 1200) + 1 + (t.val + 1200)) <
      4 * product 5 (lossCutoff (t.val + 1200) + 1) := by
  decide

theorem loss_sign_1400 : ∀ t : Fin 200,
    4 * product 5 (lossCutoff (t.val + 1400)) <
      product 5 (lossCutoff (t.val + 1400) + (t.val + 1400)) ∧
    product 5 (lossCutoff (t.val + 1400) + 1 + (t.val + 1400)) <
      4 * product 5 (lossCutoff (t.val + 1400) + 1) := by
  decide

theorem loss_sign_1600 : ∀ t : Fin 200,
    4 * product 5 (lossCutoff (t.val + 1600)) <
      product 5 (lossCutoff (t.val + 1600) + (t.val + 1600)) ∧
    product 5 (lossCutoff (t.val + 1600) + 1 + (t.val + 1600)) <
      4 * product 5 (lossCutoff (t.val + 1600) + 1) := by
  decide

theorem loss_sign_1800 : ∀ t : Fin 200,
    4 * product 5 (lossCutoff (t.val + 1800)) <
      product 5 (lossCutoff (t.val + 1800) + (t.val + 1800)) ∧
    product 5 (lossCutoff (t.val + 1800) + 1 + (t.val + 1800)) <
      4 * product 5 (lossCutoff (t.val + 1800) + 1) := by
  decide

theorem loss_sign_2000 : ∀ t : Fin 200,
    4 * product 5 (lossCutoff (t.val + 2000)) <
      product 5 (lossCutoff (t.val + 2000) + (t.val + 2000)) ∧
    product 5 (lossCutoff (t.val + 2000) + 1 + (t.val + 2000)) <
      4 * product 5 (lossCutoff (t.val + 2000) + 1) := by
  decide

theorem loss_sign_2200 : ∀ t : Fin 200,
    4 * product 5 (lossCutoff (t.val + 2200)) <
      product 5 (lossCutoff (t.val + 2200) + (t.val + 2200)) ∧
    product 5 (lossCutoff (t.val + 2200) + 1 + (t.val + 2200)) <
      4 * product 5 (lossCutoff (t.val + 2200) + 1) := by
  decide

theorem loss_sign_2400 : ∀ t : Fin 200,
    4 * product 5 (lossCutoff (t.val + 2400)) <
      product 5 (lossCutoff (t.val + 2400) + (t.val + 2400)) ∧
    product 5 (lossCutoff (t.val + 2400) + 1 + (t.val + 2400)) <
      4 * product 5 (lossCutoff (t.val + 2400) + 1) := by
  decide

theorem loss_sign_2600 : ∀ t : Fin 200,
    4 * product 5 (lossCutoff (t.val + 2600)) <
      product 5 (lossCutoff (t.val + 2600) + (t.val + 2600)) ∧
    product 5 (lossCutoff (t.val + 2600) + 1 + (t.val + 2600)) <
      4 * product 5 (lossCutoff (t.val + 2600) + 1) := by
  decide

theorem loss_sign_2800 : ∀ t : Fin 200,
    4 * product 5 (lossCutoff (t.val + 2800)) <
      product 5 (lossCutoff (t.val + 2800) + (t.val + 2800)) ∧
    product 5 (lossCutoff (t.val + 2800) + 1 + (t.val + 2800)) <
      4 * product 5 (lossCutoff (t.val + 2800) + 1) := by
  decide


theorem loss_sign_certificates : ∀ d ∈ Finset.Icc 600 2999,
    4 * product 5 (lossCutoff d) < product 5 (lossCutoff d + d) ∧
      product 5 (lossCutoff d + 1 + d) < 4 * product 5 (lossCutoff d + 1) := by
  intro d hd
  obtain ⟨hl, hu⟩ := Finset.mem_Icc.mp hd
  by_cases h600 : d < 800
  ·
    have h := loss_sign_600 ⟨d - 600, by omega⟩
    have he : d - 600 + 600 = d := by omega
    simpa only [he] using h
  by_cases h800 : d < 1000
  ·
    have h := loss_sign_800 ⟨d - 800, by omega⟩
    have he : d - 800 + 800 = d := by omega
    simpa only [he] using h
  by_cases h1000 : d < 1200
  ·
    have h := loss_sign_1000 ⟨d - 1000, by omega⟩
    have he : d - 1000 + 1000 = d := by omega
    simpa only [he] using h
  by_cases h1200 : d < 1400
  ·
    have h := loss_sign_1200 ⟨d - 1200, by omega⟩
    have he : d - 1200 + 1200 = d := by omega
    simpa only [he] using h
  by_cases h1400 : d < 1600
  ·
    have h := loss_sign_1400 ⟨d - 1400, by omega⟩
    have he : d - 1400 + 1400 = d := by omega
    simpa only [he] using h
  by_cases h1600 : d < 1800
  ·
    have h := loss_sign_1600 ⟨d - 1600, by omega⟩
    have he : d - 1600 + 1600 = d := by omega
    simpa only [he] using h
  by_cases h1800 : d < 2000
  ·
    have h := loss_sign_1800 ⟨d - 1800, by omega⟩
    have he : d - 1800 + 1800 = d := by omega
    simpa only [he] using h
  by_cases h2000 : d < 2200
  ·
    have h := loss_sign_2000 ⟨d - 2000, by omega⟩
    have he : d - 2000 + 2000 = d := by omega
    simpa only [he] using h
  by_cases h2200 : d < 2400
  ·
    have h := loss_sign_2200 ⟨d - 2200, by omega⟩
    have he : d - 2200 + 2200 = d := by omega
    simpa only [he] using h
  by_cases h2400 : d < 2600
  ·
    have h := loss_sign_2400 ⟨d - 2400, by omega⟩
    have he : d - 2400 + 2400 = d := by omega
    simpa only [he] using h
  by_cases h2600 : d < 2800
  ·
    have h := loss_sign_2600 ⟨d - 2600, by omega⟩
    have he : d - 2600 + 2600 = d := by omega
    simpa only [he] using h
  have h := loss_sign_2800 ⟨d - 2800, by omega⟩
  have he : d - 2800 + 2800 = d := by omega
  simpa only [he] using h

theorem not_four_loss_finite (n d : ℕ) (hd : 5 ≤ d) (hd' : d < 3000) :
    (∏ r ∈ Finset.Icc 1 (5 : ℕ), (n + d + r)) ≠
      4 * (∏ r ∈ Finset.Icc 1 (5 : ℕ), (n + r)) := by
  by_cases hsmall : d < 600
  · exact not_four_small_displacement n d hd hsmall
  · obtain ⟨hl, hu⟩ := loss_sign_certificates d (Finset.mem_Icc.mpr ⟨by omega, by omega⟩)
    exact not_four_of_adjacent_signs 5 d (lossCutoff d) n hl hu

/-- info: 'B686Round4K5Finite.loss_sign_certificates' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms loss_sign_certificates
/-- info: 'B686Round4K5Finite.not_four_loss_finite' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms not_four_loss_finite

end B686Round4K5Finite
