#!/usr/bin/env python3
"""Compare different actual paths without trusting recorded PASS strings."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def require(test: bool, message: str) -> None:
    if not test: raise ValueError(message)

def main() -> None:
    three=json.loads((ROOT/'outputs/three_index_certificate.json').read_text())
    seven=json.loads((ROOT/'outputs/seven_index_certificate.json').read_text())
    by_i={p['i']:p for p in seven['profiles']}
    steps=0
    for old in three['profiles']:
        new=by_i[old['i']]
        require(len(old['stages'])==len(new['bound_stages']), 'contraction length')
        for a,b in zip(old['stages'],new['bound_stages']):
            for key in ('H','M','start','next_H'):
                require(int(a[key])==int(b[key]),f'explicit vs CRT {key}')
            steps+=1
        for key in ('candidate_intervals','top_prime_intervals','large_divisor_rows','summary'):
            require(old[key]==new[key],f'explicit vs CRT terminal {key}')
    references=[]
    for filename in ('crt_bound_probe.json','crt_other_bounds.json'):
        references.extend(json.loads((ROOT/'outputs'/filename).read_text()))
    reference_steps=0
    for old in references:
        match=[s for s in by_i[old['i']]['bound_stages'] if s['H']==old['H']]
        require(len(match)==1,'general CRT reference stage not found')
        for key in ('M','start','next_H','prime_power_families','prime_power_pairs',
                    'nonempty_CRT_families','progression_terms_with_multiplicity'):
            require(int(old[key])==int(match[0][key]),f'general vs accelerated CRT {key}')
        reference_steps+=1
    result={'status':'PASS','explicit_vs_CRT_indices':[27,30,33],
            'explicit_vs_CRT_stages':steps,'saved_general_CRT_reference_stages':reference_steps,
            'note':'The two final paths are regenerated by reproduce.py. Slow general CRT reference outputs are from preserved earlier actual runs; this command compares them, not reruns them.'}
    (ROOT/'outputs/path_comparison.json').write_text(json.dumps(result,indent=2)+'\n')
    print(json.dumps(result,indent=2))
if __name__=='__main__':main()
